# Generated by Django 2.1.4 on 2019-01-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visualtable',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('writer', models.CharField(max_length=2000)),
                ('writedate', models.DateTimeField(verbose_name='date published')),
                ('hit', models.IntegerField()),
            ],
        ),
    ]
