# Generated by Django 2.0.7 on 2019-01-03 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_auto_20190103_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
