# Generated by Django 2.0.7 on 2019-01-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0003_auto_20190103_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
