# Generated by Django 2.0.7 on 2019-01-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
